// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoOrganizer.Infrastructure.Data;

#nullable disable

namespace VideoOrganizer.Infrastructure.Migrations
{
    [DbContext(typeof(VideoOrganizerDbContext))]
    [Migration("20260426163357_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoOrganizer.Domain.Models.PropertyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("TagGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagGroupId");

                    b.HasIndex("Scope", "TagGroupId", "Name")
                        .IsUnique();

                    b.ToTable("property_definitions", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TagGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagGroupId", "Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("DisplayAsCheckboxes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag_groups", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.TagPropertyValue", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.HasKey("TagId", "PropertyDefinitionId");

                    b.HasIndex("PropertyDefinitionId");

                    b.ToTable("tag_property_values", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AudioStreamCount")
                        .HasColumnType("integer");

                    b.Property<long>("Bitrate")
                        .HasColumnType("bigint");

                    b.Property<string>("CameraType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChapterMarkers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("ClipEndSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClipStartSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<double>("FrameRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IngestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("MarkedForDeletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Md5")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Md5Failed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Md5FailedError")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid?>("ParentVideoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Ratio")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("ThumbnailsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ThumbnailsFailedError")
                        .HasColumnType("text");

                    b.Property<bool>("ThumbnailsGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("VideoBlocks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("VideoDimensionFormat")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VideoQuality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("VideoStreamCount")
                        .HasColumnType("integer");

                    b.Property<int>("WatchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<bool>("WontPlay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("IngestDate");

                    b.HasIndex("Md5");

                    b.HasIndex("ParentVideoId");

                    b.HasIndex("FilePath", "FileName")
                        .IsUnique()
                        .HasFilter("\"ParentVideoId\" IS NULL");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.VideoPropertyValue", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.HasKey("VideoId", "PropertyDefinitionId");

                    b.HasIndex("PropertyDefinitionId");

                    b.ToTable("video_property_values", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.VideoSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("video_sets", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.VideoTag", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("VideoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("video_tags", (string)null);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.PropertyDefinition", b =>
                {
                    b.HasOne("VideoOrganizer.Domain.Models.TagGroup", "TagGroup")
                        .WithMany("PropertyDefinitions")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.Tag", b =>
                {
                    b.HasOne("VideoOrganizer.Domain.Models.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.TagPropertyValue", b =>
                {
                    b.HasOne("VideoOrganizer.Domain.Models.PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoOrganizer.Domain.Models.Tag", "Tag")
                        .WithMany("PropertyValues")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyDefinition");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.Video", b =>
                {
                    b.HasOne("VideoOrganizer.Domain.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("ParentVideoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.VideoPropertyValue", b =>
                {
                    b.HasOne("VideoOrganizer.Domain.Models.PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoOrganizer.Domain.Models.Video", "Video")
                        .WithMany("PropertyValues")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyDefinition");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.VideoTag", b =>
                {
                    b.HasOne("VideoOrganizer.Domain.Models.Tag", "Tag")
                        .WithMany("VideoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoOrganizer.Domain.Models.Video", "Video")
                        .WithMany("VideoTags")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.Tag", b =>
                {
                    b.Navigation("PropertyValues");

                    b.Navigation("VideoTags");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.TagGroup", b =>
                {
                    b.Navigation("PropertyDefinitions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("VideoOrganizer.Domain.Models.Video", b =>
                {
                    b.Navigation("PropertyValues");

                    b.Navigation("VideoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
